FROM ubuntu:trusty

RUN apt-get update
RUN apt-get -y install curl
RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo bash - 
RUN apt-get -y install python build-essential nodejs nginx
RUN apt-get -y install git

WORKDIR /usr/src/site

COPY package.json .
COPY package-lock.json .

RUN npm i

COPY . .
EXPOSE 8089
CMD ["/usr/src/site/node_modules/.bin/webpack-dev-server"]