version: '3'
services:
  site:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: boilerplate-site
    environment:
      - NODE_ENV=production
  selenium:
    image: selenium/standalone-firefox:3.7.1-beryllium
    container_name: selenium
    ports: 
      - 4444:4444
  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    container_name: boilerplate-e2e
    environment:
      - CODECEPT_ARGS=--debug --steps
    volumes:
      - ./:/usr/src/site
    depends_on:
      - selenium
      - site